FROM apache/airflow:2.8.0-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

USER airflow
COPY --chown=airflow:root requirements-airflow.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
